spring.application.name=Canara-Bank

spring.datasource.url=jdbc:mysql://localhost:3306/Canara_bank
spring.datasource.username=root
spring.datasource.password=root@627
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

jwt.secret=ZyXwVuTsRqPoNmLkJiHgFeDcBa9876543210qwertyuiopasdfghjklzxcvbnm