spring.application.name=Canara-Bank

spring.datasource.url=jdbc:mysql://localhost:3306/Canara_bank
spring.datasource.username=root
spring.datasource.password=root@627
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ali.java00@gmail.com
spring.mail.password=bvok wufa khuj kklp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret=ZyXwVuTsRqPoNmLkJiHgFeDcBa9876543210qwertyuiopasdfghjklzxcvbnm